### ISSUE TITLE
Issue with war integration

### ISSUE THREAD

**Issue by datbates** [EtienneMiret/sass-gradle-plugin#14]
Thanks for your plugin.  We have configured it in this way so that we can have tomcat live host our source (jsp project)

compileSass {
    sourceDir = project.file("site/scss")
    outputDir = project.file("site/styles")
}

However your plugin adds the contents of site/styles to the root of the war file.   I don't think that is what was intended.   Thanks for your help!

**Comment by EtienneMiret** [comment]
Hi @datbates!

Thank you for reporting this issue. So:
 - your sass files are under `${projectDir}/site/scss` and
 - you want the generated CSS to be inside the war under `site/styles`.

Is that right?

Unfortunately, there is no option (at the moment) to customize the location of the CSS inside the war. The `outputDir` option sets the location of the temporary folder where the `compileSass` task generates the CSS and where the war task will pick it up. Customizing the CSS location inside the war can still be achieved by creating a directory hierarchy under `sourceDir`.

In case I understood your issue correctly, I can add this option for version 1.2.0.

Otherwise, please add some details about what you are trying to achieve or about what is the actual behavior. Using your configuration, the expected behavior is that the CSS is generated under `${projectDir}/site/styles` and copied to the root of the war. When trying to reproduce your issue, this is indeed what I see happening.

Regards,

**Comment by datbates** [comment]
It sounds like that is what we would like.   We are upgrading our previous
build to use gradle.  We have always had jsp, scss, styles, and script
folders in the root of our war.  It seems strange to me to have the
compiled code in a directory under the sourceDirectory (you have to ignore
in version control and delete manually in clean right).  I know that
strange convention is not your invention, but it doesn't seem right to me
or my team.  I would love to have that feature in the future.  Thanks for
your consideration!

**Comment by datbates** [comment]
Oh, and for example, what I am seeing is the following.  It is possible
that it is an issue with our new build scripts in general.

Here is what our site directory looks like after build.  We host this in
tomcat on developer boxes by hard coding this directory into our tomcat
server.xml file and it works great there.  The styles properly contains the
.css and .map files

[image: image.png]

But inside our war we get this mess in the root.  If I prevent your plugin
from updating the war tasks "from"  I don't have this issue.

[image: image.png]

Thanks again!

**Comment by EtienneMiret** [comment]
Your images didn’t make it through, so I’m not sure what you meant in your last message.

Otherwise, version 1.2.0 was just released. It adds a new parameter `destPath` to `CompileSass` tasks that can be used to customize the CSS directory inside the war.

I think what you want can now be achieve with the configuration below:

```groovy
compileSass {
  sourceDir = project.file ("${projectDir}/site/styles")
  destPath = "site/styles"
}
```

Can you please test this and let me know if it works for you?

**Comment by datbates** [comment]
Thanks.  We tried it out and it works.  Have a great day!

**Comment by EtienneMiret** [comment]
Great! You’re welcome.
