### ISSUE TITLE
Sass compile time is too long

### ISSUE THREAD

**Issue by tungNhMor** [EtienneMiret/sass-gradle-plugin#25]
When I use the plugin on windows OS with ubuntu 20.04 the compile time is too long.
- Window : I turned off compiling when time passed, and it still outputs
-Ubuntu : I turn off compiling when the time is long, and no output.

**Comment by EtienneMiret** [comment]
Hello @tungNhMor!

Do you `watch ()` for changes in your task by any chance? If so, the build is not expected to finish until you kill it.

Otherwise, you’re not giving me much information here. When you say "on windows OS with ubuntu 20.04", you mean you are using the Windows Linux subsystem, right? Can you reproduce this issue in a sample project you could share? Have you tried to compile with sass without this plugin, to see if the issue is in the plugin or in sass?

Regards,

**Comment by tungNhMor** [comment]
good morning @EtienneMiret 

I was very excited and appreciated very much about you.

Regarding the above problem I followed you and removed watch(), it was solved.

thanks a lot!
