### ISSUE TITLE
Question regarding gradle output to downloadSass  task 

### ISSUE THREAD

**Issue by turchinc** [EtienneMiret/sass-gradle-plugin#38]
I use the plugin in a multiproject build and it works well. I have one question about efficiency. On every build for every project I see

```

> Task :project1:downloadSass UP-TO-DATE
Download https://github.com/sass/dart-sass/releases/download/1.54.4/dart-sass-1.54.4-windows-x64.zip
> Task :project2:downloadSass UP-TO-DATE
Download https://github.com/sass/dart-sass/releases/download/1.54.4/dart-sass-1.54.4-windows-x64.zip
> Task :project2:downloadSass UP-TO-DATE
Download https://github.com/sass/dart-sass/releases/download/1.54.4/dart-sass-1.54.4-windows-x64.zip
```

Is the artifact "UP-TO-DATE"? Or is the build downloading the file each time?

**Comment by EtienneMiret** [comment]
If you use the plugin in multiple subprojects, you should apply it to the root project (or a common ancestor), so that sass is downloaded once for all subprojects, instead of once per subproject. See [README](https://github.com/EtienneMiret/sass-gradle-plugin?tab=readme-ov-file#in-a-multi-projects-build) as well as issue #23.

However, whether you apply my plugin to each subproject or only to the root project, it should download sass (once per application) only during the first build, and then cache it.

**Comment by turchinc** [comment]
@EtienneMiret Many thanks for the feedback (and the plugin!). My situation is a bit complicated: The subprojects also can be build standalone (which is the more standard use case) and therefore the plugin is configured separately in each project, we only run in multiproject when doing CI builds and that is where I was seeing it.
