### ISSUE TITLE
Add example with full Gradle build setup

### ISSUE THREAD

**Issue by gandreadis** [EtienneMiret/sass-gradle-plugin#9]
It would be great if there could be an "examples" folder with at least one example of a full setup (with `build.gradle`) using this plugin. Currently, I'm struggling with getting the `compileSass` task to run on build, so I'd appreciate some example material to see how this should be done.

**Comment by EtienneMiret** [comment]
Hi @gandreadis. Are you using the war plugin?

Currently, the `compileSass` is made a dependency of each `War` task, and the output of the `compileSass` task is added to the inputs of each `War` task. This ensure that compiled CSS files are put in the war artifacts. However, if you have no `War` task at all, the `compileSass` task is not run by default.

So, my guess is you’re not using the war plugin. In that case, I’m interested to know what is your use case, so I could support it out of the box. Maybe you have a Spring Boot runable jar ?

**Comment by gandreadis** [comment]
Hi @EtienneMiret, thanks for responding! I'm not using the war plugin, but I am using the Kotlin DSL, which is a big part of the struggle, I think. I cannot share the source or JAR for now (closed source), but a very basic example with how to set it up would suffice :)

**Comment by EtienneMiret** [comment]
I’m not familiar with the Kotlin DSL, but if you want to include the compiled CSS into the `static` directory of a jar, the Groovy DSL would look like:

```build.gradle
jar {
    dependsOn compileSass
    into ('static') {
        from compileSass.outputDir
    }
}
```

**Comment by mahieddine** [comment]
The Style enum in CompileSass task should be public 

```java
public class CompileSass extends DefaultTask {

  private final WorkerExecutor workerExecutor;

  enum Style {
    expanded,
    compressed
  }
```

Because in Kotelin since it's statically typed you can't use this enum to set the style property hence making the plugin partially unusable on Kotelin

**Comment by eframsergio** [comment]
Hi @EtienneMiret, 

I'm a gradle novice and I'm currently attempting to have my scss files converted to css upon saving changes, just as I had it using a run configuration in eclipse.

I'm currently using netbeans v12.4 on a gradle web project. I originally thought that it could be automatically done by the IDE, since the css preprocessor settings (e.g. path to sass executable and input and output properties) ARE available on the IDE, but no "run configurations". Maybe the settings are there so that a sass compiler plugin can pick them up or something.

So I guess the only route to have this working is by installing an sass compiler plugin.

So I configured my build.gradle file to as follows:

```
plugins {
    id 'java'
    id 'jacoco'
    id 'war'
    id 'io.miret.etienne.sass' version '1.1.1'
}

```
and then pasted your configuration example (just changed my paths) as follows:

```
compileSass {
  // Directory where to output generated CSS:
  outputDir = project.file ("${projectDir}/src/main/webapp/resources/layout/css")

  // Source directory containing sass to compile:
  sourceDir = project.file ("${projectDir}/src/main/webapp/resources/layout/sass")

  // Adds a directory to sass load path (default is empty):
  loadPath project.file ('sass-lib')
  loadPath project.file ('/var/lib/compass')

  // Set the output style:
  // Possible values are “expanded” and “compressed”, default is “expanded”.
  style = expanded

  // Don’t emit a @charset for CSS with non-ASCII chars (default to emit):
  noCharset ()

  // When an error occurs, do not emit a stylesheet describing it:
  // (Default to emit)
  noErrorCss ()

  // Watch sass files in sourceDir for changes
  watch ()

  // Source map style:
  //  - file: output source map in a separate file (default)
  //  - embed: embed source map in CSS
  //  - none: do not emit source map.
  sourceMap = file

  // How to link source maps to source files [relative (default) or absolute]:
  sourceMapUrls = relative
}

```
I then run the `compileSass` task directly from the netbeans IDE (Project->Run Gradle->Tasks...) and get following message after a few seconds:

`Sass is watching for changes. Press Ctrl-C to stop.`

I then went to change a file and after saving it, the `Build (Project Web Store) Task :compileSass` progress bar at the bottom right started to flash by, but wouldn't stop after a long while. I could not stop the tasks by hitting the stop button. So after a while, I closed out netbeans.

Now, when I go back into netbeans and start the task `compileSass`, the progress bar endlessly cycles without stopping. It seems like something got stock there from the first action after I forcefully exited the IDE and after restaring netbeans and the `compileSass `task, it picks up where it left off.

What do you think? Do you think you can point me in the right direction. I would appreciate it very much!

Best regards,

**Comment by Riyyi** [comment]
I also had a little trouble getting it working, I have a standard Gradle Android app which doesnt use a `War` task.
Got it working with the following `Groovy` in `app/build.gradle`:
```
tasks.whenTaskAdded { task ->
    if (task.name == 'mergeDebugAssets') { mergeDebugAssets.dependsOn(compileSass) }
    if (task.name == 'mergeReleaseAssets') { mergeReleaseAssets.dependsOn(compileSass) }
}
```
If you don't have your CSS inside the `app/src/main/assets` directory you can replace the tasks with `assembleDebug` and `assembleRelease`.
